//! Executable registry for the bounded PKI differential corpus (#348).

pub const Profile = enum { core, extended };

pub const Category = enum {
    valid_chain,
    malformed_der,
    unknown_critical_extension,
    duplicate_extension,
    identity,
    cross_signing,
    name_constraints,
    path_length,
    algorithm_failure,
};

pub const Decision = enum { accept, reject };

pub const Decisions = struct {
    tardigrade: Decision,
    openssl: Decision,
    go: Decision,

    pub fn all(decision: Decision) Decisions {
        return .{
            .tardigrade = decision,
            .openssl = decision,
            .go = decision,
        };
    }

    pub fn agree(self: Decisions) bool {
        return self.tardigrade == self.openssl and self.openssl == self.go;
    }
};

pub const Case = struct {
    id: []const u8,
    profile: Profile,
    category: Category,
    root_file: []const u8,
    intermediate_file: ?[]const u8 = null,
    leaf_file: []const u8,
    dns_name: ?[]const u8 = null,
    expected: Decisions,
    /// Required whenever the three expected decisions differ. This is the
    /// explicit policy-normalization record, never an implicit waiver.
    normalization: ?[]const u8 = null,
    provenance: []const u8,
    license: []const u8,
    /// Focused unit/fuzz destination for any reduced disagreement.
    regression_target: []const u8,
};

const nc = "src/pki/testdata/name_constraints";
const hostile = "tests/vectors/pki";

pub const cases = [_]Case{
    .{
        .id = "valid-intermediate-chain",
        .profile = .core,
        .category = .valid_chain,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/valid-leaf.crt",
        .dns_name = "api.example.test",
        .expected = .all(.accept),
        .provenance = "Deterministic project-owned Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/path_builder_tests.zig and src/pki/path_validator_tests.zig",
    },
    .{
        .id = "identity-wildcard-one-label",
        .profile = .core,
        .category = .identity,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/wildcard-leaf.crt",
        .dns_name = "api.example.test",
        .expected = .all(.accept),
        .provenance = "Deterministic project-owned Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/identity_tests.zig",
    },
    .{
        .id = "identity-wildcard-apex",
        .profile = .core,
        .category = .identity,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/wildcard-leaf.crt",
        .dns_name = "example.test",
        .expected = .all(.reject),
        .provenance = "Deterministic project-owned Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/identity_tests.zig",
    },
    .{
        .id = "identity-wildcard-multiple-labels",
        .profile = .extended,
        .category = .identity,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/wildcard-leaf.crt",
        .dns_name = "deep.api.example.test",
        .expected = .all(.reject),
        .provenance = "Deterministic project-owned Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/identity_tests.zig",
    },
    .{
        .id = "unknown-critical-extension",
        .profile = .core,
        .category = .unknown_critical_extension,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/unknown-critical-leaf.crt",
        .dns_name = "critical.example.test",
        .expected = .all(.reject),
        .provenance = "Deterministic project-owned Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/path_validator_tests.zig",
    },
    .{
        .id = "duplicate-critical-extension",
        .profile = .core,
        .category = .duplicate_extension,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/duplicate-extension-leaf.crt",
        .dns_name = "duplicate.example.test",
        .expected = .all(.reject),
        .provenance = "Deterministic project-owned DER-mutated Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/x509_tests.zig and src/pki/path_validator_tests.zig",
    },
    .{
        .id = "corrupt-certificate-signature",
        .profile = .core,
        .category = .algorithm_failure,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/intermediate.crt",
        .leaf_file = hostile ++ "/signature-corrupt-leaf.crt",
        .dns_name = "api.example.test",
        .expected = .all(.reject),
        .provenance = "Deterministic project-owned Ed25519 fixture with one signature bit changed; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/verify_tests.zig",
    },
    .{
        .id = "path-length-zero-violation",
        .profile = .core,
        .category = .path_length,
        .root_file = hostile ++ "/root.crt",
        .intermediate_file = hostile ++ "/pathlen-chain.crt",
        .leaf_file = hostile ++ "/pathlen-leaf.crt",
        .dns_name = "pathlen.example.test",
        .expected = .all(.reject),
        .provenance = "Deterministic project-owned Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/path_validator_tests.zig",
    },
    .{
        .id = "ambiguous-cross-signed-path",
        .profile = .extended,
        .category = .cross_signing,
        .root_file = hostile ++ "/cross-roots.crt",
        .intermediate_file = hostile ++ "/cross-untrusted-b-first.crt",
        .leaf_file = hostile ++ "/cross-leaf.crt",
        .dns_name = "cross.example.test",
        .expected = .all(.accept),
        .provenance = "Deterministic project-owned dual-root Ed25519 fixture; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/path_builder_tests.zig",
    },
    .{
        .id = "malformed-truncated-certificate",
        .profile = .core,
        .category = .malformed_der,
        .root_file = hostile ++ "/root.crt",
        .leaf_file = hostile ++ "/malformed-truncated.crt",
        .expected = .all(.reject),
        .provenance = "Project-owned reduced malformed DER seed; see tests/vectors/pki/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/x509_tests.zig fuzz corpus",
    },
    .{
        .id = "name-constraints-dns-permitted",
        .profile = .core,
        .category = .name_constraints,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/intermediate.crt",
        .leaf_file = nc ++ "/dns-good.crt",
        .dns_name = "api.example.com",
        .expected = .{ .tardigrade = .accept, .openssl = .accept, .go = .reject },
        .normalization = "Go crypto/x509 rejects the intermediate's critical directoryName constraint as an unhandled extension; Tardigrade and OpenSSL implement this RFC 5280 form.",
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/name_constraints.zig and src/pki/identity_tests.zig",
    },
    .{
        .id = "name-constraints-dns-excluded",
        .profile = .core,
        .category = .name_constraints,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/intermediate.crt",
        .leaf_file = nc ++ "/dns-excluded.crt",
        .dns_name = "blocked.example.com",
        .expected = .all(.reject),
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/name_constraints.zig",
    },
    .{
        .id = "identity-san-mismatch",
        .profile = .core,
        .category = .identity,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/intermediate.crt",
        .leaf_file = nc ++ "/dns-good.crt",
        .dns_name = "wrong.example.com",
        .expected = .all(.reject),
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/identity_tests.zig",
    },
    .{
        .id = "name-constraints-ip-permitted-boundary",
        .profile = .core,
        .category = .name_constraints,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/intermediate.crt",
        .leaf_file = nc ++ "/ip-good.crt",
        .expected = .{ .tardigrade = .accept, .openssl = .accept, .go = .reject },
        .normalization = "Go crypto/x509 rejects the intermediate's critical directoryName constraint as an unhandled extension; Tardigrade and OpenSSL implement this RFC 5280 form.",
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/name_constraints.zig",
    },
    .{
        .id = "name-constraints-ip-excluded",
        .profile = .core,
        .category = .name_constraints,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/intermediate.crt",
        .leaf_file = nc ++ "/ip-bad.crt",
        .expected = .all(.reject),
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/name_constraints.zig",
    },
    .{
        .id = "name-constraints-leading-dot-subdomain",
        .profile = .extended,
        .category = .name_constraints,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/leading-dot-intermediate.crt",
        .leaf_file = nc ++ "/leading-dot-subdomain.crt",
        .dns_name = "sub.example.com",
        .expected = .all(.accept),
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/name_constraints.zig",
    },
    .{
        .id = "name-constraints-leading-dot-exact",
        .profile = .extended,
        .category = .name_constraints,
        .root_file = nc ++ "/root.crt",
        .intermediate_file = nc ++ "/leading-dot-intermediate.crt",
        .leaf_file = nc ++ "/leading-dot-exact.crt",
        .dns_name = "example.com",
        .expected = .all(.reject),
        .provenance = "Project-owned OpenSSL-generated RFC 5280 fixture; see src/pki/testdata/name_constraints/README.md",
        .license = "Apache-2.0",
        .regression_target = "src/pki/name_constraints.zig",
    },
};
