const std = @import("std");
const compat = @import("zig_compat");
const Headers = @import("headers.zig").Headers;

pub const HEADER_NAME = "X-Correlation-ID";
pub const REQUEST_HEADER_NAME = "X-Request-ID";
pub const MAX_CORRELATION_ID_LEN: usize = 128;

/// Validate that an incoming correlation ID matches the Tardigrade format:
///   tg-<decimal-timestamp>-<lowercase-hex>
///
/// Enforcing this format means only IDs generated by Tardigrade itself are
/// reflected back to clients and written to logs. Arbitrary client-supplied
/// strings are rejected and replaced with a freshly generated ID, preventing
/// correlation-ID spoofing and log-poisoning attacks (WSTG-INPV-11, ASVS-7.1.1).
///
/// The format is deliberately narrow: the `tg-` prefix is the namespace, the
/// decimal part is a millisecond timestamp, and the hex part is 8 random bytes
/// encoded as 16 lowercase hex characters.
pub fn isValid(id: []const u8) bool {
    // Must start with "tg-"
    if (!std.mem.startsWith(u8, id, "tg-")) return false;
    const rest = id["tg-".len..];

    // Find the second dash separating timestamp from hex suffix
    const dash = std.mem.findScalar(u8, rest, '-') orelse return false;
    const timestamp_part = rest[0..dash];
    const hex_part = rest[dash + 1 ..];

    // Timestamp part: 1–20 decimal digits
    if (timestamp_part.len == 0 or timestamp_part.len > 20) return false;
    for (timestamp_part) |c| {
        if (!std.ascii.isDigit(c)) return false;
    }

    // Hex part: 1–64 lowercase hex characters, no uppercase
    if (hex_part.len == 0 or hex_part.len > 64) return false;
    for (hex_part) |c| {
        if (!((c >= '0' and c <= '9') or (c >= 'a' and c <= 'f'))) return false;
    }

    return true;
}

/// Return client-provided correlation ID if valid; otherwise generate one.
pub fn fromHeadersOrGenerate(allocator: std.mem.Allocator, headers: *const Headers) ![]u8 {
    if (headers.get("x-request-id")) |incoming| {
        if (isValid(incoming)) {
            return allocator.dupe(u8, incoming);
        }
    }
    if (headers.get("x-correlation-id")) |incoming| {
        if (isValid(incoming)) {
            return allocator.dupe(u8, incoming);
        }
    }
    return generate(allocator);
}

/// Generate a compact ID suitable for logs and response headers.
pub fn generate(allocator: std.mem.Allocator) ![]u8 {
    var random: [8]u8 = undefined;
    compat.randomBytes(&random);
    return std.fmt.allocPrint(allocator, "tg-{d}-{f}", .{
        compat.milliTimestamp(),
        compat.fmtSliceHexLower(&random),
    });
}

test "isValid accepts Tardigrade-format IDs" {
    const testing = std.testing;
    // Valid: tg-<digits>-<hex>
    try testing.expect(isValid("tg-1778460305668-bfebecb410803023"));
    try testing.expect(isValid("tg-0-a"));
    try testing.expect(isValid("tg-1234567890-deadbeef01234567"));
}

test "isValid rejects non-Tardigrade IDs and injection payloads" {
    const testing = std.testing;
    // Missing prefix
    try testing.expect(!isValid(""));
    try testing.expect(!isValid("req-123"));
    try testing.expect(!isValid("abc-123_DEF.9"));
    // Prefix but malformed structure
    try testing.expect(!isValid("tg-"));
    try testing.expect(!isValid("tg-nodash"));
    try testing.expect(!isValid("tg--nodecimal"));
    // Uppercase hex (not generated by Tardigrade)
    try testing.expect(!isValid("tg-123-DEADBEEF"));
    // Log-poisoning payloads — rejected by format enforcement
    try testing.expect(!isValid("tg-1-a\r\nInjected: header"));
    try testing.expect(!isValid("tg-1-a\nInjected"));
    try testing.expect(!isValid("arbitrary-client-value"));
    try testing.expect(!isValid("bad space"));
    try testing.expect(!isValid("bad:colon"));
}

test "fromHeadersOrGenerate reuses valid Tardigrade-format incoming header" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var headers = Headers.init(allocator);
    defer headers.deinit();
    // Valid tg- format — should be accepted and reused
    try headers.append("X-Correlation-ID", "tg-1778460305668-bfebecb410803023");

    const correlation_id = try fromHeadersOrGenerate(allocator, &headers);
    defer allocator.free(correlation_id);

    try testing.expectEqualStrings("tg-1778460305668-bfebecb410803023", correlation_id);
}

test "fromHeadersOrGenerate prefers valid X-Request-ID over X-Correlation-ID" {
    const testing = std.testing;
    const allocator = testing.allocator;

    var headers = Headers.init(allocator);
    defer headers.deinit();
    try headers.append("X-Request-ID", "tg-111-aabbccdd");
    try headers.append("X-Correlation-ID", "tg-222-11223344");

    const correlation_id = try fromHeadersOrGenerate(allocator, &headers);
    defer allocator.free(correlation_id);

    try testing.expectEqualStrings("tg-111-aabbccdd", correlation_id);
}

test "fromHeadersOrGenerate ignores arbitrary client-supplied IDs and generates fresh" {
    const testing = std.testing;
    const allocator = testing.allocator;

    // Non-tg-format strings are rejected — fresh ID generated
    var headers_bad = Headers.init(allocator);
    defer headers_bad.deinit();
    try headers_bad.append("X-Correlation-ID", "user-controlled-value");

    const id1 = try fromHeadersOrGenerate(allocator, &headers_bad);
    defer allocator.free(id1);
    try testing.expect(std.mem.startsWith(u8, id1, "tg-"));
    try testing.expect(isValid(id1));

    // Uppercase hex — not generated by Tardigrade, must be rejected
    var headers_upper = Headers.init(allocator);
    defer headers_upper.deinit();
    try headers_upper.append("X-Correlation-ID", "tg-123-DEADBEEF");

    const id2 = try fromHeadersOrGenerate(allocator, &headers_upper);
    defer allocator.free(id2);
    try testing.expect(std.mem.startsWith(u8, id2, "tg-"));
    try testing.expect(isValid(id2));
}
